import requests
import json
import time

API_URL = "http://localhost:8000/borrowers/apply"

borrowers = [
    {
        "full_name": "John Doe",
        "email": "john.doe@logistics.com",
        "mobile_no": "555-0101",
        "business_name": "Doe Logistics LLC",
        "dba_name": "Doe Express",
        "business_state": "TX",
        "zip_code": "75001",
        "years_in_business": 5.0,
        "business_entity_type": "LLC",
        "industry_tier": 3,
        "industry_naics": "484121",
        "annual_revenue": 500000,
        "avg_daily_balance": 15000,
        "nsf_count": 0,
        "dscr_ratio": 1.3,
        "guarantor_fico": 720,
        "ownership_percentage": 100,
        "paynet_score": 680,
        "is_homeowner": True,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 85000,
        "ltv_ratio": 100,
        "equipment_type": "Trucking",
        "equipment_condition": "used",
        "equipment_age": 4,
        "vendor_type": "Dealer",
        "equipment_location_state": "TX"
    },
    {
        "full_name": "Sarah Smith",
        "email": "sarah@medicorp.com",
        "mobile_no": "555-0102",
        "business_name": "Smith Medical Services",
        "dba_name": "Surgical Specialists",
        "business_state": "CA",
        "zip_code": "90210",
        "years_in_business": 12.0,
        "business_entity_type": "Corp",
        "industry_tier": 1,
        "industry_naics": "621111",
        "annual_revenue": 1200000,
        "avg_daily_balance": 45000,
        "nsf_count": 0,
        "dscr_ratio": 1.8,
        "guarantor_fico": 780,
        "ownership_percentage": 50,
        "paynet_score": 750,
        "is_homeowner": True,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 250000,
        "ltv_ratio": 90,
        "equipment_type": "Medical",
        "equipment_condition": "new",
        "equipment_age": 0,
        "vendor_type": "Dealer",
        "equipment_location_state": "CA"
    },
    {
        "full_name": "Mike Builder",
        "email": "mike@buildit.com",
        "mobile_no": "555-0103",
        "business_name": "Mike's Construction",
        "dba_name": "Mike Builds",
        "business_state": "FL",
        "zip_code": "33101",
        "years_in_business": 2.0,
        "business_entity_type": "Sole Prop",
        "industry_tier": 2,
        "industry_naics": "236115",
        "annual_revenue": 250000,
        "avg_daily_balance": 5000,
        "nsf_count": 2,
        "dscr_ratio": 1.1,
        "guarantor_fico": 640,
        "ownership_percentage": 100,
        "paynet_score": 580,
        "is_homeowner": False,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": True,
        "years_since_last_judgment": 1,
        "loan_amount": 45000,
        "ltv_ratio": 80,
        "equipment_type": "Construction",
        "equipment_condition": "used",
        "equipment_age": 7,
        "vendor_type": "Private Party",
        "equipment_location_state": "FL"
    },
    {
        "full_name": "Emily Green",
        "email": "emily@greenacres.com",
        "mobile_no": "555-0104",
        "business_name": "Green Acres Farming",
        "dba_name": "GAF",
        "business_state": "NE",
        "zip_code": "68001",
        "years_in_business": 25.0,
        "business_entity_type": "Partnership",
        "industry_tier": 2,
        "industry_naics": "111150",
        "annual_revenue": 800000,
        "avg_daily_balance": 10000,
        "nsf_count": 0,
        "dscr_ratio": 1.25,
        "guarantor_fico": 690,
        "ownership_percentage": 33,
        "paynet_score": 645,
        "is_homeowner": True,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 120000,
        "ltv_ratio": 100,
        "equipment_type": "Agricultural",
        "equipment_condition": "used",
        "equipment_age": 2,
        "vendor_type": "Dealer",
        "equipment_location_state": "NE"
    },
    {
        "full_name": "Robert Risky",
        "email": "rob@freshstart.com",
        "mobile_no": "555-0105",
        "business_name": "Fresh Start Hauling",
        "dba_name": "",
        "business_state": "NY",
        "zip_code": "10001",
        "years_in_business": 1.5,
        "business_entity_type": "LLC",
        "industry_tier": 3,
        "industry_naics": "484110",
        "annual_revenue": 150000,
        "avg_daily_balance": 2000,
        "nsf_count": 5,
        "dscr_ratio": 0.9,
        "guarantor_fico": 580,
        "ownership_percentage": 100,
        "paynet_score": 0,
        "is_homeowner": False,
        "has_active_bankruptcy": True,
        "years_since_bankruptcy_discharge": 0,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 35000,
        "ltv_ratio": 50,
        "equipment_type": "Trucking",
        "equipment_condition": "used",
        "equipment_age": 8,
        "vendor_type": "Dealer",
        "equipment_location_state": "NY"
    },
    {
        "full_name": "Lisa Tech",
        "email": "lisa@innovate.com",
        "mobile_no": "555-0106",
        "business_name": "Innovate Solutions",
        "dba_name": "InnovateMed",
        "business_state": "WA",
        "zip_code": "98101",
        "years_in_business": 8.0,
        "business_entity_type": "Corp",
        "industry_tier": 1,
        "industry_naics": "541511",
        "annual_revenue": 2000000,
        "avg_daily_balance": 80000,
        "nsf_count": 0,
        "dscr_ratio": 2.5,
        "guarantor_fico": 810,
        "ownership_percentage": 80,
        "paynet_score": 820,
        "is_homeowner": True,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 500000,
        "ltv_ratio": 100,
        "equipment_type": "Medical",
        "equipment_condition": "new",
        "equipment_age": 0,
        "vendor_type": "Dealer",
        "equipment_location_state": "WA"
    },
    {
        "full_name": "Carlos Concrete",
        "email": "carlos@paving.com",
        "mobile_no": "555-0107",
        "business_name": "Carlos Paving",
        "dba_name": "CP Concrete",
        "business_state": "AZ",
        "zip_code": "85001",
        "years_in_business": 15.0,
        "business_entity_type": "LLC",
        "industry_tier": 2,
        "industry_naics": "237310",
        "annual_revenue": 600000,
        "avg_daily_balance": 12000,
        "nsf_count": 1,
        "dscr_ratio": 1.15,
        "guarantor_fico": 660,
        "ownership_percentage": 100,
        "paynet_score": 615,
        "is_homeowner": True,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 7,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 95000,
        "ltv_ratio": 90,
        "equipment_type": "Construction",
        "equipment_condition": "used",
        "equipment_age": 5,
        "vendor_type": "Dealer",
        "equipment_location_state": "AZ"
    },
    {
        "full_name": "Amanda Retail",
        "email": "amanda@boutique.com",
        "mobile_no": "555-0108",
        "business_name": "Amanda's Boutique",
        "dba_name": "A-Style",
        "business_state": "GA",
        "zip_code": "30301",
        "years_in_business": 3.0,
        "business_entity_type": "Sole Prop",
        "industry_tier": 3,
        "industry_naics": "448120",
        "annual_revenue": 180000,
        "avg_daily_balance": 3000,
        "nsf_count": 0,
        "dscr_ratio": 1.05,
        "guarantor_fico": 710,
        "ownership_percentage": 100,
        "paynet_score": 0,
        "is_homeowner": False,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 25000,
        "ltv_ratio": 100,
        "equipment_type": "Trucking",
        "equipment_condition": "new",
        "equipment_age": 0,
        "vendor_type": "Dealer",
        "equipment_location_state": "GA"
    },
    {
        "full_name": "Kevin Heavy",
        "email": "kevin@heavyhaul.com",
        "mobile_no": "555-0109",
        "business_name": "Heavy Haul Inc",
        "dba_name": "",
        "business_state": "OH",
        "zip_code": "43001",
        "years_in_business": 20.0,
        "business_entity_type": "Corp",
        "industry_tier": 3,
        "industry_naics": "484230",
        "annual_revenue": 3000000,
        "avg_daily_balance": 25000,
        "nsf_count": 0,
        "dscr_ratio": 1.4,
        "guarantor_fico": 680,
        "ownership_percentage": 25,
        "paynet_score": 710,
        "is_homeowner": True,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 180000,
        "ltv_ratio": 85,
        "equipment_type": "Trucking",
        "equipment_condition": "used",
        "equipment_age": 3,
        "vendor_type": "Private Party",
        "equipment_location_state": "OH"
    },
    {
        "full_name": "Nancy Newbie",
        "email": "nancy@startup.com",
        "mobile_no": "555-0110",
        "business_name": "Nancy's Startup",
        "dba_name": "Newbie Tech",
        "business_state": "NV",
        "zip_code": "89101",
        "years_in_business": 0.5,
        "business_entity_type": "LLC",
        "industry_tier": 2,
        "industry_naics": "541611",
        "annual_revenue": 80000,
        "avg_daily_balance": 5000,
        "nsf_count": 0,
        "dscr_ratio": 1.2,
        "guarantor_fico": 740,
        "ownership_percentage": 100,
        "paynet_score": 0,
        "is_homeowner": False,
        "has_active_bankruptcy": False,
        "years_since_bankruptcy_discharge": 99,
        "has_unpaid_tax_liens": False,
        "years_since_last_judgment": 99,
        "loan_amount": 30000,
        "ltv_ratio": 100,
        "equipment_type": "Construction",
        "equipment_condition": "new",
        "equipment_age": 0,
        "vendor_type": "Dealer",
        "equipment_location_state": "NV"
    }
]


def run_seed():
    print(f"🚀 Starting batch submission of {len(borrowers)} borrowers...")
    print(f"📡 Target API: {API_URL}")
    print("-" * 50)
    
    success_count = 0
    fail_count = 0
    
    for i, borrower in enumerate(borrowers, 1):
        print(f"Processing {i}/{len(borrowers)}: {borrower['business_name']}...")
        
        try:
            response = requests.post(
                API_URL, 
                headers={"Content-Type": "application/json"},
                data=json.dumps(borrower),
                timeout=10
            )
            # print(type(response)) 
            data = response.json()
            if data['success'] == True:
                print("done: ", data['message'])
            else:
                print("Something went wrong")
                
        except Exception as e:
            print(e)
            
        time.sleep(0.2)

    print("-" * 50)

if __name__ == "__main__":
    run_seed()